[package]
name = "the-boss"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk = { version = "0.29.0", features = [ "compiler" ] }
bitcoin = { version = "0.32.2", features = [ "bitcoinconsensus" ] }
