[workspace]
members = ["hub", "browser-wallet", "tests-e2e", "mempool-mock", "descriptor-wallet", "pay-with-moon"]
resolver = "2"

[profile.release]
opt-level = "s"

[patch.crates-io]
xtra = { git = "https://github.com/Restioson/xtra/", rev = "3714ce8" }
