services:
  db:
    container_name: postgres
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./services/database/:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_USER: hub

volumes:
  postgres:
