# Inspired by https://github.com/EmbarkStudios/rust-ecosystem/pull/68.
# tokio_unstable enabled for tokio_console and tokio_metrics only
[build]
rustflags = [
  "-Wclippy::disallowed_methods",
  "-Wclippy::dbg_macro",
  "-Wclippy::print_stderr",
  "-Wclippy::print_stdout",
  "-Wunused-import-braces",
  "-Wunused-qualifications",
  "-Wclippy::unwrap_used",
]

[target.'cfg(feature = "cargo-clippy")']
rustflags = [
  "-Wclippy::disallowed_methods",
  "-Wclippy::dbg_macro",
  "-Wclippy::print_stderr",
  "-Wclippy::print_stdout",
  "-Wunused-import-braces",
  "-Wunused-qualifications",
  "-Wclippy::unwrap_used",
]
