[package]
name = "tests-e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
hub = { path = "../hub" }
borrower-wallet = { path = "../borrower-wallet" }
tokio = { version = "1", features = ["full", "tracing"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12.7", features = ["cookies", "json"] }
