// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/take-offer": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/app" | "/take-offer";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app";
  };
  "routes/take-offer.tsx": {
    id: "routes/take-offer";
    page: "/take-offer";
  };
};