-- Step 1: Drop the autogenerated 'id' column
ALTER TABLE transactions
    DROP COLUMN id;

-- Step 2: Rename 'txid' back to 'id'
ALTER TABLE transactions
    RENAME COLUMN txid TO id;

-- Step 3: Re-add the primary key constraint on the 'id' column
ALTER TABLE transactions
    ADD PRIMARY KEY (id);
