
ALTER TABLE INVITE_CODES RENAME TO INVITE_CODES_BORROWER;

CREATE TABLE INVITE_CODES_LENDER
(
    id     SERIAL PRIMARY KEY,
    code   VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL
);

INSERT INTO INVITE_CODES_LENDER (code, active) VALUES ('IMONFIRE2024', true);

ALTER TABLE lenders
    DROP CONSTRAINT IF EXISTS lenders_invite_code_fkey;

ALTER TABLE lenders
    ADD CONSTRAINT lenders_invite_code_fkey
        FOREIGN KEY (invite_code) REFERENCES INVITE_CODES_LENDER(id);

