ALTER TABLE IF EXISTS INVITE_CODES_BORROWER RENAME TO INVITE_CODES;

ALTER TABLE lenders
    DROP CONSTRAINT IF EXISTS lenders_invite_code_fkey;

ALTER TABLE lenders
    ADD CONSTRAINT lenders_invite_code_fkey
        FOREIGN KEY (invite_code) REFERENCES invite_codes(id);

DROP TABLE IF EXISTS INVITE_CODES_LENDER;
