-- Add up migration script here

CREATE TABLE
    IF NOT EXISTS "users"
(
    -- TODO: use autogenerated ID here
    id                   CHAR(36) PRIMARY KEY     NOT NULL,
    name                 VARCHAR(100)             NOT NULL,
    email                VARCHAR(255)             NOT NULL UNIQUE,
    password             VARCHAR(100)             NOT NULL,
    verified             BOOLEAN                  NOT NULL DEFAULT FALSE,
    verification_code    VARCHAR(255),
    password_reset_token VARCHAR(50),
    password_reset_at    TIMESTAMP WITH TIME ZONE          DEFAULT CURRENT_TIMESTAMP,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX users_email_idx ON users (email);
CREATE INDEX idx_verification_code ON users (verification_code);
CREATE INDEX idx_password_reset_token ON users (password_reset_token);
CREATE INDEX idx_password_reset_at ON users (password_reset_at);
