CREATE TABLE
    IF NOT EXISTS "lenders"
(
    -- TODO: use autogenerated ID here
    id                   CHAR(36) PRIMARY KEY     NOT NULL,
    name                 VARCHAR(100)             NOT NULL,
    email                VARCHAR(255)             NOT NULL UNIQUE,
    password             VARCHAR(100)             NOT NULL,
    verified             BOOLEAN                  NOT NULL DEFAULT FALSE,
    verification_code    VARCHAR(255),
    password_reset_token VARCHAR(50),
    password_reset_at    TIMESTAMP WITH TIME ZONE          DEFAULT CURRENT_TIMESTAMP,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE loan_offers
    DROP CONSTRAINT IF EXISTS loan_offers_lender_id_fkey;

ALTER TABLE loan_offers
    ADD CONSTRAINT loan_offers_lender_id_fkey
        FOREIGN KEY (lender_id) REFERENCES lenders (id);

ALTER TABLE contracts
    DROP CONSTRAINT IF EXISTS contracts_lender_id_fkey;

ALTER TABLE contracts
    ADD CONSTRAINT contracts_lender_id_fkey
        FOREIGN KEY (lender_id) REFERENCES lenders (id);