use crate::db;
use crate::model::ApiKeyInfo;
use crate::model::Lender;
use crate::routes::lender::auth::jwt_auth;
use crate::routes::lender::API_KEYS_TAG;
use crate::routes::AppState;
use axum::extract::rejection::JsonRejection;
use axum::extract::FromRequest;
use axum::extract::Path;
use axum::extract::State;
use axum::middleware;
use axum::response::IntoResponse;
use axum::response::Response;
use axum::Extension;
use axum::Json;
use reqwest::StatusCode;
use serde::Deserialize;
use serde::Serialize;
use std::sync::Arc;
use tracing::instrument;
use utoipa::ToSchema;
use utoipa_axum::router::OpenApiRouter;
use utoipa_axum::routes;

pub(crate) fn router(app_state: Arc<AppState>) -> OpenApiRouter {
    OpenApiRouter::new()
        .routes(routes!(get_api_keys))
        .routes(routes!(post_api_key))
        .routes(routes!(delete_api_key))
        .route_layer(middleware::from_fn_with_state(
            app_state.clone(),
            jwt_auth::auth,
        ))
        .with_state(app_state.clone())
}

/// Get all personal API keys.
#[utoipa::path(
    get,
    path = "/",
    tag = API_KEYS_TAG,
    responses(
        (
            status = 200,
            description = "List of API keys",
            body = [ApiKeyInfo]
        )
    ),
    security(
        ("api_key" = [])
    )
)]
#[instrument(skip_all, err(Debug))]
async fn get_api_keys(
    State(data): State<Arc<AppState>>,
    Extension(user): Extension<Lender>,
) -> Result<AppJson<Vec<ApiKeyInfo>>, Error> {
    let api_keys = db::api_keys::get_api_keys_lender(&data.db, &user.id)
        .await
        .map_err(Error::database)?;

    Ok(AppJson(api_keys))
}

/// Create a new API key.
#[utoipa::path(
    post,
    request_body = NewApiKey,
    path = "/",
    tag = API_KEYS_TAG,
    responses(
        (
            status = 200,
            description = "API key created successfully"
        )
    ),
    security(
        ("api_key" = [])
    )
)]
#[instrument(skip_all, err(Debug))]
async fn post_api_key(
    State(data): State<Arc<AppState>>,
    Extension(user): Extension<Lender>,
    AppJson(body): AppJson<NewApiKey>,
) -> Result<(), Error> {
    db::api_keys::insert_lender(&data.db, &body.api_key_hash, &user.id, &body.description)
        .await
        .map_err(Error::database)?;

    Ok(())
}

/// Delete an API key.
#[utoipa::path(
    delete,
    path = "/{id}",
    tag = API_KEYS_TAG,
    params(
        ("id" = String, Path, description = "API key ID")
    ),
    responses(
        (
            status = 200,
            description = "API key deleted successfully"
        )
    ),
    security(
        ("api_key" = [])
    )
)]
#[instrument(skip_all, err(Debug))]
async fn delete_api_key(
    State(data): State<Arc<AppState>>,
    Extension(user): Extension<Lender>,
    Path(id): Path<i32>,
) -> Result<(), Error> {
    db::api_keys::delete_lender(&data.db, &user.id, id)
        .await
        .map_err(Error::database)?;

    Ok(())
}

#[derive(Debug, Deserialize, ToSchema)]
struct NewApiKey {
    /// SHA256 of the API key secret, generated by the client.
    api_key_hash: String,
    /// Purpose of the API key.
    description: String,
}

/// All the errors related to the `keys` REST API.
#[derive(Debug)]
enum Error {
    /// The request body contained invalid JSON.
    JsonRejection(JsonRejection),
    /// Failed to interact with the database.
    Database(#[allow(dead_code)] String),
}

impl Error {
    fn database(e: impl std::fmt::Display) -> Self {
        Self::Database(format!("{e:#}"))
    }
}

impl From<JsonRejection> for Error {
    fn from(rejection: JsonRejection) -> Self {
        Self::JsonRejection(rejection)
    }
}

// Create our own JSON extractor by wrapping `axum::Json`. This makes it easy to override the
// rejection and provide our own which formats errors to match our application.
//
// `axum::Json` responds with plain text if the input is invalid.
#[derive(Debug, FromRequest)]
#[from_request(via(Json), rejection(Error))]
struct AppJson<T>(T);

impl<T> IntoResponse for AppJson<T>
where
    Json<T>: IntoResponse,
{
    fn into_response(self) -> Response {
        Json(self.0).into_response()
    }
}

/// Tell `axum` how [`Error`] should be converted into a response.
impl IntoResponse for Error {
    fn into_response(self) -> Response {
        /// How we want error responses to be serialized.
        #[derive(Serialize)]
        struct ErrorResponse {
            message: String,
        }

        let (status, message) = match self {
            Error::JsonRejection(rejection) => {
                // This error is caused by bad user input so don't log it
                (rejection.status(), rejection.body_text())
            }
            Error::Database(_) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                "Something went wrong".to_owned(),
            ),
        };

        (status, AppJson(ErrorResponse { message })).into_response()
    }
}
