name: "Deploy hub binary to test VM"

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up rust toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v1

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Build browser wallet
        run: just build-wallet

      - name: Install frontend deps
        run: |
          cd frontend-monorepo
          pnpm install

      - name: Make .env file for Vite build
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_BORROWER_BASE_URL: "https://borrow.signet.lendasat.com"
          envkey_VITE_LENDER_BASE_URL: "https://lend.signet.lendasat.com"
          envkey_VITE_BITCOIN_NETWORK: "signet"
          envkey_VITE_MEMPOOL_REST_URL: "https://mutinynet.com"
          envkey_VITE_TELEGRAM_BOT_URL: "https://t.me/lendasatsignetlenderbot"
          envkey_VITE_TELEGRAM_BOT_NAME: "@lendasatsignetlenderbot"

      - name: Build borrower frontend
        run: just build-frontend

      - name: Build hub
        run: cargo build --release --bin hub --target-dir ./target

      - name: Compress frontend directory
        run: tar -czvf hub-frontend.tar.gz ./frontend-monorepo/apps/borrower/dist ./frontend-monorepo/apps/lender/dist

      - name: Copy ssh key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.TEST_VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Upload hub-frontend.tar.gz to server
        run: |
          scp -v -o StrictHostKeyChecking=no -i /.ssh/id_rsa ./hub-frontend.tar.gz ${{secrets.TEST_VM_USERNAME}}@${{secrets.TEST_VM_SSH_HOST}}:/home/${{secrets.TEST_VM_USERNAME}}/uploads/

      - name: Create hub-frontend.confirmed file on server
        run: |
          ssh -v -o StrictHostKeyChecking=no -i  /.ssh/id_rsa ${{secrets.TEST_VM_USERNAME}}@${{secrets.TEST_VM_SSH_HOST}} 'touch /home/${{secrets.TEST_VM_USERNAME}}/uploads/hub-frontend.confirmed'

      - name: Upload hub binary to server
        run: |
          scp -v -o StrictHostKeyChecking=no -i /.ssh/id_rsa ./target/release/hub ${{secrets.TEST_VM_USERNAME}}@${{secrets.TEST_VM_SSH_HOST}}:/home/${{secrets.TEST_VM_USERNAME}}/uploads/hub

      - name: Create hub.confirmed file on server
        run: |
          ssh -v -o StrictHostKeyChecking=no -i  /.ssh/id_rsa ${{secrets.TEST_VM_USERNAME}}@${{secrets.TEST_VM_SSH_HOST}} 'touch /home/${{secrets.TEST_VM_USERNAME}}/uploads/hub.confirmed'
