name: "Deploy to mainnet"

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
      - name: Check out commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v1

      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.2

      - name: Install web deps
        run: |
          pnpm install

      - name: Set Git Variables
        id: git-vars
        run: |
          echo "GIT_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

      - name: Create .env files for apps
        run: |
          cat > .env << EOF
          VITE_BORROWER_BASE_URL=https://apiborrow.lendasat.com
          VITE_IFRAME_URL=https://iframe.lendasat.com
          EOF
          cp .env apps/iframe/.env
          cp .env apps/sample-wallet/.env

      - name: Build web apps
        run: pnpm build

      - name: Deploy iframe
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN}}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/iframe/build/client --project-name=lendasat-iframe

      - name: Deploy sample-wallet
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN}}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/sample-wallet/dist/ --project-name=lendasat-sample-wallet

        # TODO: publish new version of the bridge to npm
